spring.application.name=booker
server.port=8180

spring.datasource.url=jdbc:postgresql://localhost:5432/booker-java
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.secret="5367566859703373367639792F423F452848284D6251655468576D5A71347437"
app.accessTokenExpiresIn=60
app.refreshTokenExpiresIn=7