spring.application.name=booker
server.port=8180

spring.datasource.url=jdbc:postgresql://localhost:5432/booker-java
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=5367566859703373367639792F423F452848284D6251655468576D5A71347437
jwt.accessTokenExpiresIn=60
jwt.refreshTokenExpiresIn=7
jwt.issuer=booker-rest-api
jwt.audiance=booker-audience